### ISSUE TITLE
Custom path to Nuget.exe does not work

### ISSUE THREAD

**Issue by conficient** [landofjoe/NuspecPackager#2]
When setting the NuGet path in the Options screen I have to specify the path/folder where nuget.exe is located; e.g. `C:\NUGET`

If I do this NuspecPackager does not add 'nuget.exe' to the path and fails to find nuget.exe when instructed to pack.

If I try to enter a full path, e.g. `C:\Nuget\Nuget.exe` it disallows this saying it must be empty or specify an existing directory.

**Comment by conficient** [comment]
I have amended the code in GetItemConfig in my own fork to fix this issue. I have also changed the method used to write to the output window. I copied the Logger class from VS WebEssentials 2015 and used that. All in this commit: https://github.com/conficient/NuspecPackager/commit/00149631070f01651f0fce8d1af9ac9169a5bc86

**Comment by funky-jojo** [comment]
Thanks for the post.  I have resolved this issue by simplifying the options (removing the UseDefaultNugetExe option).
